name 'resource-helper-test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures resource-helper-test'
long_description 'Installs/Configures resource-helper-test'
version '0.1.0'
